### PR TITLE
INTRISK-43253: Add skynet.yaml to satisfy release automation

### PR DESCRIPTION
**Pull request by robbecker-wf**
# [INTRISK-43253](https://jira.atl.workiva.net/browse/INTRISK-43253)
Issue Status

There are no tests, so this just runs skynet and passes to make the bots happy.

### CODE REVIEW

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit ae9ecb3cab738dc20b9de1e983ba6c36549255b2

Showing results for ae9ecb3cab738dc20b9de1e983ba6c36549255b2
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/pdfjs_dart/ae9ecb3cab738dc20b9de1e983ba6c36549255b2).

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by matthewnitschke-wk — APPROVED** [review]

**Comment by matthewnitschke-wk** [comment]
QA +1

- [x]  CI does indeed pass

🚀 @Workiva/release-management-p 🚢

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
