### PR TITLE
Implement `DocumentInitParameters`

### PR DESCRIPTION
**Pull request by seanburke-wf**
Provide support for opening documents via `DocumentInitParameters` ([documentation](https://mozilla.github.io/pdf.js/api/draft/global.html#DocumentInitParameters)). This is provided as a strongly-typed dart object which wraps a raw JS object.

Also taking this opportunity to add a couple helpful badges to the README and try to get travis passing.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by tomconnell-wf** [comment]
# +1
Everything is implemented in what looks like the correct way, except worker and CMapReaderFactory, which we don't need.

**Comment by tomconnell-wf** [comment]
# +1

**Comment by tomconnell-wf** [comment]
# +10 
I saw it work to request a pdf in w_viewer with a chunk size of ~128K instead of ~64K.

**Comment by tomconnell-wf** [comment]
# Quality Review Approval: QA +1  
- [x] Testing Instructions
- [x] Dev +1's
- [x] Dev/QA +10 detailing what was tested
- [ ] Unit tests created, updated, or explained if not present
- [x] All CI checks pass (Smithy, Shipyard, Skynet)
@Workiva/release-management-pp - Rosie, will you automerge?

**Pull request merged**
