### PR TITLE
set pre-first-release version to 0.0.0, add simple README

### PR DESCRIPTION
**Pull request by robbecker-wf**
# Tooling having trouble making a first release
Set the version to zero so internal tooling can bump it.

bonus: add a simple readme

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by seanburke-wf** [comment]
### +1

**Comment by seanburke-wf** [comment]
### QA +1
@Workiva/release-management-p for merge into master

**Comment by rmconsole-wf** [comment]
@seanburke-wf I will not merge this because: 
* 'Dependency Scan Clean' is False
* dependencies not scanned

**Comment by rmconsole-wf** [comment]
@seanburke-wf I will not merge this because: 
* 'Dependency Scan Clean' is False
* 'All commits reviewed' is False
* dependencies not scanned

**Comment by rmconsole-wf** [comment]
@seanburke-wf I will not merge this because: 
* 'Dependency Scan Clean' is False
* 'All commits reviewed' is False
* dependencies not scanned

**Comment by seanburke-wf** [comment]
### +1

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
