### PR TITLE
Change to using dart_build_image for docker

### PR DESCRIPTION
**Pull request by pauldanner-wk**

### CODE REVIEW

**Comment by semveraudit-wf** [comment]
### Public API Changes

 ## Issue: No Semver Audit Report Found for Base Commit

**Base commit:** `8658d83464cb6f751454a8cfe227dded4f93062f`

This means we couldn't find semver audit data for the commit against which to compare the changes in this PR. Fixing this is a two step process. First, we'll need to generate the semver audit data for the base commit. Then we will have to generate the semver audit data for the head commit on this branch. This can be done by rerunning CI and/or manually running the semver audit tool.

**Note: It may be sufficient to simply merge master into your branch.**

## Step 1: Generate Semver Audit Data for the Base Commit:

You can do this either by rerunning CI on the base commit or by manually running the semver audit tool locally on the base commit.

### Option 1: Rerunning CI

Locate the build associated with the base commit (8658d83464cb6f751454a8cfe227dded4f93062f) in [Workiva Build](https://ci.webfilings.com/Workiva/pdfjs_dart) and rerun it.

### Option 2: Run the Semver Audit Tool Manually

```bash
# Navigate to the root of the repo and check out the base commit:
$ git checkout 8658d83464cb6f751454a8cfe227dded4f93062f

# If this is a Dart project, run:
$ pub global run semver_audit report --repo Workiva/pdfjs_dart --head-commit 8658d83464cb6f751454a8cfe227dded4f93062f

# If this is a Go project, run:
$ semver_audit_go report  --repo Workiva/pdfjs_dart --head-commit 8658d83464cb6f751454a8cfe227dded4f93062f
```

**Note:** If this is a Dart project, the manual steps above assume you have the Dart 2 SDK installed and activated and the `semver_audit` tool globally installed. See [this Confluence post](https://wiki.atl.workiva.net/questions/104006659/how-do-i-install-dart-2-and-easily-switch-between-dart-versions) to install Dart 2. To globally install the `semver_audit` tool, run the following:

```bash
$ pub global activate --hosted-url https://pub.workiva.org semver_audit ^2.0.0
```

## Step 2: Generate Semver Audit Data for this Branch's Head Commit:

You can do this either by rerunning CI on this PR or by manually running the semver audit tool locally against the head commit on this branch.

### Option 1: Rerunning CI

This is often the easiest solution. Find the Workiva Build check on this Pull Request and simply rerun it.

### Option 2: Run the Semver Audit Tool Manually

```bash
# Navigate to the root of the repo and check out the head commit on this branch:
$ git checkout 3113d227e9a6dcd96068ff8ad93e43db3fb62b1c

# If this is a Dart project, run:
$ pub global run semver_audit report --repo Workiva/pdfjs_dart --base-commit 8658d83464cb6f751454a8cfe227dded4f93062f --head-commit 3113d227e9a6dcd96068ff8ad93e43db3fb62b1c --pull 41

# If this is a Go project, run:
$ semver_audit_go report --repo Workiva/pdfjs_dart --base-commit 8658d83464cb6f751454a8cfe227dded4f93062f --head-commit 3113d227e9a6dcd96068ff8ad93e43db3fb62b1c --pull 41
```

## Still Need Help?

If you are unable to resolve the issue on your own, either tag `@Workiva/app-frameworks` in a PR comment or reach out to us in the [#support-client-plat](https://slack.com/app_redirect?channel=CEDM9RH1N) Slack channel.


Showing results for 3113d227e9a6dcd96068ff8ad93e43db3fb62b1c
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/pdfjs_dart/3113d227e9a6dcd96068ff8ad93e43db3fb62b1c).

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by corwinsheahan-wf** [comment]
semver +1, this is the first semver run on this repo, so there is no previous base commit in this repo. This pr does not change any public API.

**Review by abigailbeets-wk — APPROVED** [review]

**Review by ryanelliott-wk — APPROVED** [review]

**Comment by ryanelliott-wk** [comment]
QA +1 
Screen Shot 2021-08-09 at 9 33 43 AM

**Comment by pauldanner-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
