### PR TITLE
Implement `PDFDocumentProxy.getOutline()` and supporting functionality

### PR DESCRIPTION
**Pull request by seanburke-wf**
Provide the necessary types and methods to support document outline and related go-to-destination functionality.

Some cleanup and a bonus API method which didn't require any type manipulation here.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by tomconnell-wf** [comment]
# +1

**Comment by tomconnell-wf** [comment]
I'm getting this on all the pdfs I try to load, consuming this and the w_viewer branch, in graph_app:

image

**Comment by tomconnell-wf** [comment]
I guess the second item isn't always a string?  https://github.com/Workiva/pdfjs_dart/pull/11/files#diff-3f35f0652f9121fd4977fbc879219b3dR66

**Comment by tomconnell-wf** [comment]
# +1
On Sean's changes

**Comment by seanburke-wf** [comment]
### +1
On Tom's change

**Comment by tomconnell-wf** [comment]
# Quality Review Approval: QA +1  
- [x] Testing Instructions
- [x] Dev +1's
- [x] Dev/QA +10 detailing what was tested
- [ ] Unit tests created, updated, or explained if not present
- [x] All CI checks pass (Smithy, Shipyard, Skynet)
@Workiva/release-management-pp - Rosie, will you automerge?

**Pull request merged**
