### PR TITLE
upgrade node

### PR DESCRIPTION
**Pull request by ryanelliott-wk**
Builds are failing - upgrading node to a more recent version seems to resolve issue

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by patkujawa-wf — APPROVED** [review]

**Comment by patkujawa-wf** [comment]
QA +1 CI passed

**Comment by patkujawa-wf** [comment]
Weird that there's no rosie comment

**Comment by patkujawa-wf** [comment]
Rosie, how about now?

**Comment by patkujawa-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
