### PR TITLE
Start action conversion

### PR DESCRIPTION
**Pull request by jayudey-wf**
Utilizing github actions for our build processes

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit 2bfe4f457e6de0fe8c21e9780a699fafaa163c2a

Showing results for 2bfe4f457e6de0fe8c21e9780a699fafaa163c2a
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/pdfjs_dart/2bfe4f457e6de0fe8c21e9780a699fafaa163c2a).

**Review by pauldanner-wk — APPROVED** [review]
LGTM

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
