### PR TITLE
Release pdfjs_dart 2.5.207

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [CPLAT-8327: Post-Dart2 cleanup](https://github.com/Workiva/pdfjs_dart/pull/24)
	* [upgrade node](https://github.com/Workiva/pdfjs_dart/pull/32)
	* [[INTRISK-28406] Upgrade Pdfjs interop to v2.5.207 from markup_client](https://github.com/Workiva/pdfjs_dart/pull/35)

Requested by: @pauldanner-wk

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/pdfjs_dart/compare/2.1.266...Workiva:release_pdfjs_dart_2.1.267
Diff Between Last Tag and New Tag: https://github.com/Workiva/pdfjs_dart/compare/2.1.266...2.1.267

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6568135994376192/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6568135994376192/?pull_number=37&repo_name=Workiva%2Fpdfjs_dart)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by pauldanner-wk — APPROVED** [review]

**Comment by patkujawa-wf** [comment]
2.5.207 or 2.1.267?

**Comment by pauldanner-wk** [comment]
Should be 2.5.207, as it seems like what this repo has done is followed the pdfjs version, I updated the package.json, but for some reason, it didn't update this right for the pubspec?

**Comment by patkujawa-wf** [comment]
@pauldanner-wk yeah, you probably will need to do that manually.

**Comment by patkujawa-wf** [comment]
Actually, lemme try having marv create the PR agaiin

**Comment by patkujawa-wf** [comment]
https://github.com/Workiva/pdfjs_dart/pull/38

**Review by patkujawa-wf — APPROVED** [review]

**Comment by pauldanner-wk** [comment]
Perfect. Thanks Pat! So can we close this one then?

**Pull request closed without merging**
